language: generic

# Getting permissions
sudo: required
# Get Copy of Docker ready
services: 
  - docker

before_install:
  # Added Tag for otherwise imageId will be generated-used within travis ci
  - docker build -t rossferreira/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rossferreira/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-252383048810"
  bucket_path: "docker-react"
  # Only deply changes to Master Branch
  on: 
    branch: master
  # Keys will come from local env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY